package enums;

public enum ResponseType {
    SUCCESS,
    ERROR,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ONLINE_PLAYERS,
    LEADERBOARD,
    REGISTER_SUCCESS,
    USER_EXISTS,
    INVALID_DATA,
    ALREADY_LOGGED_IN,
    GAME_INVITE,
    INVITE_RECEIVED,
    INVITE_ACCEPTED,
    INVITE_REJECTED,
    MOVE_MADE,
    JOIN_GAME,
    GAME_OVER
}
